# Generated by Django 5.1.5 on 2025-01-23 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0001_initial'),
        ('user', '0001_initial'),
    ]
    operations = [
        migrations.AlterField(
            model_name='blog',
            name='dislikes',
            field=models.ManyToManyField(related_name='user_dislikes', to='user.profile'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='likes',
            field=models.ManyToManyField(related_name='user_likes', to='user.profile'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blogging.comment'),
        ),
    ]
